### ISSUE TITLE
ubuntu snappy core ?

### ISSUE THREAD

**Issue by gedw99** [gliderlabs/docker-alpine#111]
alpine is great for sure. cant complain about 5 mb.
But what are your thoughts on ubuntu snappy ?
i am interested in using it because it has transactional AB updates and provisioning system, which is good for clouds where some of the servers are not in a  data center but out in the field.

**Comment by andyshinn** [comment]
I wrote a 5 paragraph explanation of my thoughts on Ubuntu Snappy Core vs Alpine Linux. But then I realized (after reading it aloud to myself), that I've become too desensitized of Docker in general over the last year. So, I'd rather just leave this question open to others and hear *their* thoughts on Ubuntu Snappy Core, which will probably answer the question and help everyone understand the landscape a little more.

**Comment by jbergknoff** [comment]
@andyshinn I'd like to read that post if you still have it around. This is the first time I've heard of Ubuntu Snappy Core.

**Comment by joeblew99** [comment]
Me too.

I am currently using Ubuntu core and coreos.

Coreos because it allows me to update remote out in the field servers fully from the OS up with rollback.

Ubuntu core because it allows me the same as what coreos gives me, but for arm embedded devices.

Being able to do a full OS update with rollback is important for high quality projects.

Docker can run on both easily of course.

Ultimately I am converging to move fully to the Ubuntu core snappy on data Center servers, remote servers and remote devices. This way I can use the same architecture everywhere.

The code that makes snappy do its thing is mostly written in golang, which I program in, and so its very comfortable / reassuring to use

**Comment by Conan-Kudo** [comment]
@joeblew99 I've been mainly pulling this off with Atomic, and the rpm-ostree stuff makes it easy to compose atomic systems for any purpose, not just Docker hosts.

**Comment by joeblew99** [comment]
Atomic. Mhh
It needs redhat ?
Can you send me some links ?

**Comment by andyshinn** [comment]
Here are some good articles to read about the other minimalist host operating systems: 

* https://blog.docker.com/2015/02/the-new-minimalist-operating-systems/
* https://blog.inovex.de/docker-a-comparison-of-minimalistic-operating-systems/

I think the main distinction between Alpine and these specialized minimal container host solutions is just that, they are specialized to be a product of something (Snappy from Ubuntu, Photon from VMware, Atomic from RedHat). Alpine is just naturally small and lightweight. It isn't the small, specialized, lightweight product of a former larger offering.

Also, in the context of the Docker image (and I speak for myself here), I am using it exclusively as a base for containers where static compiled binaries don't quite work out or I need additional utilities along with my application. CoreOS, Snappy, Photon, Atomic, et al. are exclusively host operating systems (to my knowledge) and can't really even be a base for a container.

Though, to that extent, I personally haven't used anything other than CoreOS and Ubuntu and my time on CoreOS wasn't that pleasant (though I still follow it and hope I can get to use it again someday). I'm also a huge fan of the work the guys (and gals) over at Rancher Labs are doing and am waiting for the opportunity to give RancherOS a good shakedown.
