### ISSUE TITLE
Push latest/3.3 image with Alpine 3.3.1

### ISSUE THREAD

**Issue by mhart** [gliderlabs/docker-alpine#129]
I'm sure this is on the TODO list of someone already, but just in case it's not...

http://www.alpinelinux.org/posts/Alpine-3.3.1-released.html

**Comment by andyshinn** [comment]
It doesn't look like any packages in the base image are affected by 3.3.1. Since we require and `apk update` anyways (which will get the newest package index and packages), do we even think this is necessary?

**Comment by mhart** [comment]
Hmmm, so you're saying there's zero difference to the image 74e49af2062e pushed two weeks ago?

**Comment by andyshinn** [comment]
Correct, there doesn't appear to be any base changes:

```
docker run alpine:3.3 apk -U version
```

**Comment by mhart** [comment]
No probs – wasn't sure how you tracked Alpine releases. If you don't actually track Alpine releases, then I'm happy to close this.

**Comment by andyshinn** [comment]
It is more complicated than that. Alpine releases are really just a set of packages (usually the`alpine-base`, `musl`, `musl-utils`, `busybox`, and `apk-tools` packages will get you a working container). Their repositories only track the major.minor version. So, 3.3.1 in this case are just new packages in the 3.3 repository.

Since we only install `alpine-baselayout`, `musl`, `musl-utils`, `busybox`, and `apk-tools` in the base image, if none of these packages change in patch versions, then there isn't anything to rebuild in the image.

The more complicated part is that we pull down `alpine-base` and extract the contents of `/etc` so that we have a proper `/etc/os-release` file (we don't actually install `alpine-base` since it has a ton of dependencies we don't need). So, until the 3.3 image is rebuilt, the `/etc/os-release` file will say 3.3.0. But the set of packages you are downloading are from the 3.3 repository, which is all the packages at the time of the 3.3.1 release.

**Comment by mhart** [comment]
Right, I mean, it sounds like it doesn't *need* to be complicated. Like, you could just release a new build whenever Alpine has a release. If nothing but the `/etc/os-release` file changes, then all the better, you don't even need to worry about possible unknown breakages, etc – but at least your users know their image is up to date.

I don't really have a strong opinion on it, I just know that the Docker image appeared to be out of date to me because I knew 3.3.1 was the latest release – I can't really speak for anyone else as to whether they might have the same thought.

**Comment by andyshinn** [comment]
Yes, we could be more automated and just roll a release when Alpine has a release as well. I'll look into ways we might be able to hook into their build system and maybe trigger a PR or something to tell us of a release.

**Comment by ncopa** [comment]
We publish mqtt messages when there are new releases that you probably could hook up to

**Comment by andyshinn** [comment]
Cool! How can I get access to it to play with it and see the topics? I didn't see anything on the wiki. Let me know if I should post to dev mailing list.

I also pushed a bumped 3.3 image for 3.3.1 and opened the official library request at https://github.com/docker-library/official-images/pull/1353.

**Comment by andyshinn** [comment]
3.3.1 pushed to official repository. I'm talking to ncopa offline about MQTT messages and how I might be able to leverage them.
