### ISSUE TITLE
Generate image tags like Alpine versions (x.y.z)

### ISSUE THREAD

**Issue by nlamirault** [gliderlabs/docker-alpine#138]
According to Alpine Linux website, releases use "x.y.z" pattern. The tags of Docker images are only "x.y".
Why not create the same tags to Alpine versions ?

[1] : https://www.alpinelinux.org/posts/
[2] : https://hub.docker.com/_/alpine/

**Comment by andyshinn** [comment]
See comment at https://github.com/gliderlabs/docker-alpine/issues/129#issuecomment-170984246 for a little explanation. Basically, Alpine repositories only track the minor version (x.y). The patch level revisions (.z) are mostly package changes or security updates. Those updates get pushed to the same minor revision repository (x.y). Sometimes, those patch level releases may not even affect the package versions in the Alpine base image (so there isn't any real change).

If there is a good use case for tagging them we can start doing that. But right now, 3.3.0 and 3.3.1 are releases that pull packages from the 3.3 repository, so a 3.3.0 image is the same as 3.3.1, since installing any packages would just be the latest from 3.3.1 release.

Hope this isn't too confusing...

**Comment by nlamirault** [comment]
Thanks !
