### ISSUE TITLE
dns resolving use wrong dns server

### ISSUE THREAD

**Issue by win-t** [gliderlabs/docker-alpine#217]
i have 3 entries in my /etc/resolv.conf
```
nameserver 10.231.0.2
nameserver 10.10.4.14
nameserver 10.10.33.84
```
first one is from OpenVPN, and the last 2 from my router DHCP

when i `drill codereview.srv.internal. @10.231.0.2` it work normally, but when i do `drill codereview.srv.internal.` it cannot resolve because somehow it use the second entry (10.10.4.14) as default, is it bug from libc?, because it work normally in host (using glibc 2.23)

**Comment by andyshinn** [comment]
Check out the caveats section at http://gliderlabs.viewdocs.io/docker-alpine/caveats/. The issue here is that musl libc does not query nameservers in order, they are queried in parallel. You cannot guarantee that the first nameserver will resolve first.

To get around this issue, a common pattern is to use an intermediary DNS server (such as dnsmasq or https://github.com/gliderlabs/resolvable).
