### ISSUE TITLE
Alpine for ARM

### ISSUE THREAD

**Issue by zyfdegh** [gliderlabs/docker-alpine#237]
I'm using `alpine:latest` as base image, and run container on Raspberry Pi 2(armv7l). But error occured when trying to shell into container,

```sh
$ sudo docker exec -it myalpine sh
exec format error
```
it's due to `/bin/sh` is built for Linux x86_64 I guess.

So, any idea on supporting alpine for ARM?

**Comment by justincormack** [comment]
There is a docker hub image at `armhf/alpine`.

**Comment by bluefoxicy** [comment]
It would be nice if the hub supported multi-arch registries.  I made [some comments](https://forums.docker.com/t/multi-arch-registries/26851) in that direction, but nothing close to filing a bug yet.

Ideally, something like the below would allow an `armhf` and `x86_64` architecture to both build from the same `Dockerfile`, in some imaginary future version of the Docker registry:

```Dockerfile
FROM scratch
ENV ALPINE_VERSION 3.5.0
ADD alpine-minirootfs-${ALPINE_VERSION}-${DOCKER_ARCH}.tar.gz /
```

Right now, the Hub only knows images by name and tag--it doesn't know about architecture--so no such thing will work, unfortunately.

**Comment by andyshinn** [comment]
I'll leave this open for now. But I think the limitations have already been mentioned before:

* Docker Hub (and other registries as far as I know) don't provide a way to distinguish architecture for a single repository (though, we could just as well have a special tag for arm).
* There aren't any arm builders for either Docker Hub or CircleCI. We'd need some way to automate the building of arm images.

**Comment by Tim15** [comment]
+1 for official alpine image multi-arch support.

Debian and Ubuntu both already have this.

**Comment by Tim15** [comment]
Docker Hub provides a system for official docker-library maintainers to distribute multi-arch images. When we submit an update to the docker-library repo, we can specify alternate architectures which will then get pushed to the appropriate organization on Docker Hub.

See [https://github.com/docker-library/official-images#multiple-architectures](https://github.com/docker-library/official-images#multiple-architectures)
 
For example, the debian image specifies multiple architectures in [this file](https://github.com/docker-library/official-images/blob/master/library/debian#L46), which then get pushed to the docker hub organizations [amd64](https://hub.docker.com/u/amd64/), [armv7](https://hub.docker.com/u/arm32v7/), [armv5](https://hub.docker.com/u/arm32v5/), [i386](https://hub.docker.com/u/i386/), etc

The `amd64` organization on Docker Hub is effectively the same as the regular `library` org, which is why Alpine is currently in both.

**Comment by Tim15** [comment]
As far as actually building the images, all you need to do is change the `--arch` flag on `apk fetch alpine-base` to the arch you are building. See [builder/scripts/mkimage-alpine.bash](https://github.com/gliderlabs/docker-alpine/blob/master/builder/scripts/mkimage-alpine.bash#L45)

Since we're not actually compiling anything, just downloading some files, it seems fairly simple to add multi-arch to the build proccess, if I'm not mistaken. I think this should also work on any builder architecture (even an x86_64 based CircleCI or Docker Hub builder).

The last step would be to change the library spec file generator [here](https://github.com/gliderlabs/docker-alpine/blob/master/build#L87) to include the architectures we support. 

@andyshinn If this sounds good to you, I'll start working on a PR

The last decision would probably be whether the gliderlabs images would want multiarch. This would probably be more complicated because there isn't a great place to put them.

**Comment by andyshinn** [comment]
We've completed the first release for multi-arch alpine. See #352.
