### ISSUE TITLE
Proper container init system

### ISSUE THREAD

**Issue by endersonmaia** [gliderlabs/docker-alpine#25]
Are there plans for a proper init system ? I don't know it the OpenRC can be adjusted to the docker container.

This wold be useful for things like cron, syslog (client), optional ssh.

Something like runit is used in the https://github.com/phusion/baseimage-docker

See this : https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by jumanjiman** [comment]
my 2 cents:

an init system *can* be valuable for some configurations. it gets into the "fat container" vs "thin container" discussion.

regardless of that discussion, be aware that some upcoming security standards for dockerized apps recommend the one-process-per-container approach, and security auditors will gravitate toward these standards and consider fat containers as a red flag.

therefore a "proper init system" is something that should definitely *not* be in the base image, but rather as an optional secondary image. the base image should stay slim and (easy to) secure.

**Comment by jbergknoff** [comment]
:+1: to @jumanjiman. These things do not belong in a base image.

**Comment by endersonmaia** [comment]
I think that a baseimage should provide an initsystem, and let the users choose if they'll use it or not, based on the necessity.

If my container is fine starting the app as PID 1, ok. But if I need some other process to monitor, log, or anything else, the baseimage should define what are the steps to start other processe inside the container.

The [runit](http://smarden.org/runit/) and [runit-init](http://smarden.org/runit/runit-init.8.html) are very slim, and should do the job.

**Comment by jumanjiman** [comment]
please don't misunderstand my position.
i'm not opposed to having an "alpine-runit" image that contains runit and can be used as a base image. this would be nice from the perspective of a community-endorsed, consistent starting point for people and organizations who need a proper init system for some containers.

however, runit should not be in the alpine base image itself.
if runit is there, then the mere act of removing it makes the resultant image bigger since there's an additional layer for the removal.

**Comment by progrium** [comment]
We will not add an init system to this image. Please make your own base image that has an init system if you need it. We don't encourage or support the use of containers in this way.
