### ISSUE TITLE
ADD_BASELAYOUT

### ISSUE THREAD

**Issue by honeyankit** [gliderlabs/docker-alpine#262]
While using mkimage-alpine.bash script to build alpine base image I have questions on Adding base layout:
1. What is the purpose of Adding base layout ?
apk --root "$rootfs" --keys-dir /etc/apk/keys \
                                fetch --stdout alpine-base | tar -xvz -C "$rootfs" etc

**Comment by andyshinn** [comment]
The reason for this is that the `alpine-base` package pulls in more dependencies that we don't need. But we want to populate `/etc/` with some files from `alpine-base` (namely `/etc/os-release`). So, instead of installing the package we just download and extract `/etc/` from it. If `-b` is omitted from the CLI then we will not run this step.

Hope that makes sense. Let me know if you need any clarification.
