### ISSUE TITLE
Update image to 3.1.3

### ISSUE THREAD

**Issue by pikeas** [gliderlabs/docker-alpine#27]
Released about a month ago. Image is currently running 3.1.2

**Comment by andyshinn** [comment]
The patch revision really only affects `edge` since the repositories track the minor version only (the stable package repository tracks 3.1 and not 3.1.3). Thus, a `apk add -U nginx` will be the same whether on 3.1.2 or 3.1.3. However, there have been some musl security backports to 3.1 from edge and we should get some new bases out soon.

**Comment by jumanjiman** [comment]
> there have been some musl security backports to 3.1 from edge

put this here just for the record...

info about the openssl 1.0.1m release: https://www.openssl.org/news/openssl-1.0.1-notes.html

details for security backports:

```console
core@ip-192-168-254-162 ~ $ docker run --rm -it alpine:latest sh
/ # cat /etc/apk/repositories 
http://dl-4.alpinelinux.org/alpine/v3.1/main

/ # apk upgrade -U && rm -f /var/cache/apk/*
fetch http://dl-4.alpinelinux.org/alpine/v3.1/main/x86_64/APKINDEX.tar.gz
(1/7) Upgrading musl (1.1.5-r2 -> 1.1.5-r4)
(2/7) Upgrading busybox (1.22.1-r14 -> 1.22.1-r15)
Executing busybox-1.22.1-r15.post-upgrade
(3/7) Upgrading alpine-conf (3.1.0-r2 -> 3.1.0-r4)
(4/7) Upgrading libcrypto1.0 (1.0.1k-r0 -> 1.0.1m-r1)
(5/7) Upgrading libssl1.0 (1.0.1k-r0 -> 1.0.1m-r1)
(6/7) Upgrading musl-utils (1.1.5-r2 -> 1.1.5-r4)
(7/7) Upgrading alpine-base (3.1.2-r0 -> 3.1.3-r0)
Executing busybox-1.22.1-r15.trigger
OK: 5 MiB in 15 packages
```

**Comment by andyshinn** [comment]
New `gliderlabs/alpine` images have been pushed with the edge and 3.1.3 updates.
