### ISSUE TITLE
apk fetch hangs

### ISSUE THREAD

**Issue by dkirrane** [gliderlabs/docker-alpine#307]
fetch of the apk index just hangs.  I hit this now on a Ubuntu server and Docker for Windows
```
Step 1/14 : FROM maven:3.3.9-jdk-8-alpine
 ---> dd9d4e1cd9db
Step 2/14 : RUN apk update && apk upgrade       && apk add --no-cache --update  ca-certificates         bash    wget    curl    tree    libxml2-utils   putty   git     && rm -rf /var/lib/apt/lists/*     && rm -rf /var/cache/apk/*
 ---> Running in 536cbd484c36
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
```

Docker version 17.03.1-ce, build c6d412e

**Comment by andyshinn** [comment]
Are you able to start another container shell and curl dl-cdn.alpinelinux.org? Sounds like a networking issue somewhere.

**Comment by dkirrane** [comment]
Got around this by running using https
```
RUN sed -i 's/http\:\/\/dl-cdn.alpinelinux.org/https\:\/\/alpine.global.ssl.fastly.net/g' /etc/apk/repositories
```

**Comment by charlescanato** [comment]
Doesn't seem like a DNS issue, since it has resolved. Unfortunately, for while, I'm at the same point: names are resolved, but can't connect to anything.

**Comment by andyshinn** [comment]
In another issue I thought this could be a DNS issue because the CDN POP IP addresses may change more frequently. If DNS is being cached somewhere and TTL not honored then an outdated IP address may be returned for dl-cdn.alpinelinux.org.

This is why I need debugging information to help pinpoint it. When the issue happens, I need the `curl -v -s http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz > /dev/null` output from inside a container and the host so we can compare.

**Comment by kachkaev** [comment]
Also facing this thing from time to time. Here’s a typical output of GitLab CI when fetching fails:

![screen shot 2017-10-14 at 15 19 48](https://user-images.githubusercontent.com/608862/31576457-3c3518ca-b0f3-11e7-8a9d-a1dba5be0ad8.png)

Restarting the CI job helps, but there’s no guarantee of the reliability.

**Comment by antonmarin** [comment]
how to do curl if i cannot install it?

**Comment by antonmarin** [comment]
```
/ # curl -v -s http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz > /de
v/null
*   Trying 151.101.84.249...
* TCP_NODELAY set
* Connected to dl-cdn.alpinelinux.org (151.101.84.249) port 80 (#0)
> GET /alpine/v3.5/main/x86_64/APKINDEX.tar.gz HTTP/1.1
> Host: dl-cdn.alpinelinux.org
> User-Agent: curl/7.56.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/octet-stream
< Last-Modified: Mon, 04 Dec 2017 09:08:18 GMT
< ETag: "5a251082-b3195"
< Accept-Ranges: bytes
< Content-Length: 733589
< Accept-Ranges: bytes
< Date: Mon, 04 Dec 2017 16:03:17 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-bma7035-BMA
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1512403397.178165,VS0,VE64
< 
{ [8688 bytes data]
* Connection #0 to host dl-cdn.alpinelinux.org left intact
/ # 
```
Success while another process hangs

**Comment by andremarianiello** [comment]
I ran into this issue in kubernetes. I bounced the kube-dns pod to flush any records it might be caching. This fixed the problem for me.

**Comment by nogoegst** [comment]
Are you running Docker-in-Docker by any chance? I have this issue only in dind containers.

**Comment by andremarianiello** [comment]
I only have this with dind + kubernetes. However it doesn't happen if I use '--network host' or '--net host'. I am using weave overlay network.

**Comment by nogoegst** [comment]
@andremarianiello thanks for info, I am also using dind+kubernetes (though with flannel). Have you enabled hostNetwork true for dind pods?

**Comment by andremarianiello** [comment]
@nogoegst No I haven't. It worked without doing that.

**Comment by nogoegst** [comment]
@andremarianiello so you mean you set `--network host` for dockerized docker daemon? Where did you set it?

**Comment by andremarianiello** [comment]
I added it to my docker client commands, e.g. 'docker build --network host ...'

**Comment by neclimdul** [comment]
I've see the k8s issue quite a bit. wireshark shows fastly getting stuck sending oversized packets with a do not fragment flag. I don't think this is OP's issue though as its docker for windows.

I recently started running into a similar issue to this as well though. On linux but the behavior is the same, apk fails fetching and mostly on the index. Again, pulled up wireshark and recreated the problem. I see things going smoothly then the apk process seems to stop ACK'ing segments from the fastly server. Fastly starts throttling and resending segments and it lags out.

I've never recreated this with curl, but it looks like apk uses a built in BSD libfetch for its HTTP communications so maybe there's a bug in there?

My network communication understanding is just enough to get me this far so here's a [link](https://www.dropbox.com/s/ykz0r7rgn40tmab/alpine_failure2.pcapng?dl=0) to the wireshark log of the communications. hopefully an alpine dev has a better understanding and can parse out a clue or find the problem.

**Comment by neclimdul** [comment]
Yeah I was treating this as a different issue because it has slightly different characteristics and not the same as #279.

The Wireshark link in https://github.com/gliderlabs/docker-alpine/issues/307#issuecomment-387613710 shows a different traffic behavior. Instead of the traffic doesn't get killed at the bridge, it is never ACK'd by libfetch and Fastly's TCP session gets stuck trying to get recover. I don't know if it's even fastly's fault as on the surface it seems to be doing the right thing.

```
... misc traffic 
ack:                   container -> bridge -> fastly
Transmission:          container <- bridge <- fastly
Transmission:          container <- bridge <- fastly
ack:                   container -> bridge -> fastly
Transmission:          container <- bridge <- fastly
Transmission:          container <- bridge <- fastly
ack:                   container -> bridge -> fastly
Transmission:          container <- bridge <- fastly 1
Transmission:          container <- bridge <- fastly 2
Transmission:          container <- bridge <- fastly 3
Transmission:          container <- bridge <- fastly 4
Transmission:          container <- bridge <- fastly 5
... some number of other packets
Transmission:          container <- bridge <- fastly X
Transmission:          container <- bridge <- fastly 1
Transmission:          container <- bridge <- fastly 1
Transmission:          container <- bridge <- fastly 1
Transmission:          container <- bridge <- fastly 1
Transmission:          container <- bridge <- fastly 1
Transmission:          container <- bridge <- fastly 1
Transmission:          container <- bridge <- fastly 1
Transmission:          container <- bridge <- fastly 1
.... repeat
```

**Comment by neclimdul** [comment]
observation, networking is hard.

**Comment by andremarianiello** [comment]
@evanrich My gitlab CI was using docker:dind as a service container, and my main build container had a docker client in it which I used to connect to the service container. My repo has a dockerfile in it that I need to be built by the gitlab runner. My .gitlab-ci.yaml file contained the command
```
docker build .
```
This builds my docker image. One of my layers in the dockerfile runs `apk update`. This command hangs, causing the `docker build` command and the CI as a whole to fail.
However, if I modify my .gitlab-ci.yaml file to have
```
docker build --network host .
```
docker will run the `apk update` command from my dockerfile without hanging.

**Comment by ncopa** [comment]
I believe that the problem is that in docker the MTU is lower than on the host. The way this is supposed to work is via [path MTU discovery](https://en.wikipedia.org/wiki/Path_MTU_Discovery), but fastly appears to block the PMTU icmp packet (I guess it is a part of their DDoS defence). The way to "fix" this properly is to enable MSS clamping on the host.
https://blog.ipspace.net/2013/01/tcp-mss-clamping-what-is-it-and-why-do.html

The other alternative is to use a different mirror that does not block the PMTU traffic.

**Comment by andremarianiello** [comment]
@ncopa How can we check to see if our docker mtu is lower than our host mtu?

**Comment by evanrich** [comment]
> @evanrich My gitlab CI was using docker:dind as a service container, and my main build container had a docker client in it which I used to connect to the service container. My repo has a dockerfile in it that I need to be built by the gitlab runner. My .gitlab-ci.yaml file contained the command
> 
> ```
> docker build .
> ```
> This builds my docker image. One of my layers in the dockerfile runs `apk update`. This command hangs, causing the `docker build` command and the CI as a whole to fail.
> However, if I modify my .gitlab-ci.yaml file to have
> 
> ```
> docker build --network host .
> ```
> docker will run the `apk update` command from my dockerfile without hanging.

are you not using auto devops?   I haven't specified a .gitlab-ci.yml file yet, I seem to have worked around part of it via switching to alpine.global.ssl.fastly.net, but i get this

```
Status: Downloaded newer image for golang:alpine
 ---> 95ec94706ff6
Step 2/13 : RUN sed -i 's/http\:\/\/dl-cdn.alpinelinux.org/https\:\/\/alpine.global.ssl.fastly.net/g' /etc/apk/repositories
 ---> Running in a3de349b32f8
Removing intermediate container a3de349b32f8
 ---> 39505fc0c5f2
Step 3/13 : RUN apk update;     apk add git gcc build-base;     go get -v github.com/cloudflare/cloudflared/cmd/cloudflared
 ---> Running in 548789a2500b
fetch https://alpine.global.ssl.fastly.net/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch https://alpine.global.ssl.fastly.net/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
v3.8.1-22-g24d67bab3a [https://alpine.global.ssl.fastly.net/alpine/v3.8/main]
v3.8.1-16-g96e1e57fed [https://alpine.global.ssl.fastly.net/alpine/v3.8/community]
OK: 9539 distinct packages available
(1/25) Installing binutils (2.30-r5)
```

and it just hangs at installing binutils every time.   Found this: https://github.com/gliderlabs/docker-alpine/issues/279 . seems to be a wide spread issue in k8s due to lower mtu.

I was able to get slightly further with changing my mirror from a fastly mirror to mirror.clarkson.edu using
```RUN sed -i 's/http\:\/\/dl-cdn.alpinelinux.org/http\:\/\/mirror.clarkson.edu/g' /etc/apk/repositories```

**Comment by smnbbrv** [comment]
If you come here from Drone CI and their drone plugin, set the MTU that fits you in the settings of the plugin. Probably could save you some hours of debugging and desperate attempts:

```yml
kind: pipeline
type: kubernetes
name: default

steps:
  - name: dockerize
    image: plugins/docker
    settings:
      ...
      mtu: 1000
```

**Comment by Stark-X** [comment]
Hi here, is there anyone still suffering this issue? Seems the issue has gone some how.
I can't reproduce the "hangs" now.

**Comment by smnbbrv** [comment]
20 days ago it still was present, see above

**Comment by Stark-X** [comment]
> 20 days ago it still was present, see above

It still present last week, what about these 2days? could u have a try 👀

**Comment by smnbbrv** [comment]
I tried and it worked for these two days. However hangs again now.

**Comment by akhfa** [comment]
> If you come here from Drone CI and their drone plugin, set the MTU that fits you in the settings of the plugin. Probably could save you some hours of debugging and desperate attempts:
> 
> ```yaml
> kind: pipeline
> type: kubernetes
> name: default
> 
> steps:
>   - name: dockerize
>     image: plugins/docker
>     settings:
>       ...
>       mtu: 1000
> ```

Hi, thanks for this. This help my build. I remember I found article about MTU that maybe useful to give more information
https://medium.com/@liejuntao001/fix-docker-in-docker-network-issue-in-kubernetes-cc18c229d9e5

**Comment by slaecker** [comment]
@smnbbrv Thanks a lot for the mtu hint, now drone is finally building ...

**Comment by shaopeng-lin** [comment]
I have apk fetch hangs indefinitely, it's not because of mtu but network glitch.

My alpine and apk version:
~# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.3
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

~# apk --version
apk-tools 2.10.4, compiled for x86_64.

I can reproduce the issue by just shutting down my eth when apk fetch is downloading apks.

~# apk fetch -R linux-lts
Downloading linux-firmware-sun-20191215-r0
Downloading linux-firmware-microchip-20191215-r0
Downloading linux-firmware-rtl_nic-20191215-r0
Downloading xz-libs-5.2.4-r0
Downloading linux-firmware-keyspan-20191215-r0
Downloading linux-firmware-mwlwifi-20191215-r0
Downloading linux-firmware-cpia2-20191215-r0
Downloading libcrypto1.1-1.1.1d-r3
Downloading linux-firmware-ti-connectivity-20191215-r0
Downloading linux-firmware-slicoss-20191215-r0
Downloading linux-firmware-korg-20191215-r0
Downloading linux-firmware-atmel-20191215-r0
Downloading linux-firmware-tehuti-20191215-r0
Downloading linux-firmware-nvidia-20191215-r0
Downloading linux-firmware-netronome-20191215-r0
  5% ###########      

Then I bring eth back and check network connectivity is fine.
But the apk fetch does not fail nor resume downloading.   

**UPDATE 2020-06-16:**
Since ssbarnea mentioned about IPv6, I checked my environment,
~# sysctl net.ipv6.conf.all.disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
And I am running the test from a physical server, not inside container.

**Comment by ssbarnea** [comment]
I was able to narrow down the issue and is IPv6. If docker host has IPv6 enabled you are pretty much f**** as apk fetch from inside container will get stuck trying to fetch from `dl-cdn.alpinelinux.org` which will return "dualstack" results, but we all know that IPv6 does not work in containers.

APK gets fully stuck without ever timing out or trying to to use IPv4 addresses, which will likely work.

That problem is a huge PITA as normal debugging techiniques will not give any usable results:
* using `--network host` does not matter
* using `ping` or nslookup on `dl-cdn.alpinelinux.org` from inside container works too
* Even using `wget` works (curl is absent from base image)

## UPDATE, we have a working hack
I can confirm that https://stackoverflow.com/a/41497555/99834 hack works on both docker and podman, mainly adding ``--dns-opt='options single-request' --sysctl net.ipv6.conf.all.disable_ipv6=1`` when running/building the containers.

**Comment by FabioPaes12** [comment]
Old problem, but it still happens!

For me, none of the options worked!
I will mention some of the steps that alleviated the problem and allowed me to generate the image, even after 2 or 3 attempts, which is already good, since I could not even generate the image!


1# Repository change, for any mirror, add a RUN line or Joining an existing RUN:
`echo "http://dl-4.alpinelinux.org/alpine/v3.12/main" > /etc/apk/repositories \
&& apk update` ...
The Official List is here: https://mirrors.alpinelinux.org/

2 # The one that best behaved was to change the DNS of the Image, add a RUN line or Joining an existing RUN:
`RUN printf "nameserver 208.67.222.222\nnameserver 8.8.4.4\nnameserver 1.1.1.1\nnameserver 9.9.9.9\nnameserver 8.8.8"> /etc/resolv.conf \
&& apk update && apk add ...`
*** This Line must be included for all RUNs that update.

3 # Change the Docker DNS:
In Ubuntum, just edit the file: / etc / default / docker
Ex: `sudo gedit / etc / default / docker`
E Include in the file, the Line:
`DOCKER_OPTS = "- dns 208.67.222.222 --dns 8.8.8.8 --dns 1.1.1.1 --dns 8.8.4.4 --dns 208.67.220.220 --dns 9.9.9.9"`

**Comment by pysen** [comment]
Running the offical Drone helm chart on k3os (v0.11) I had to set the MTU to 1450 for my build to finish and not stall on fetching the apkindex.
```
- name: docker-build
   image: plugins/docker
   settings:
     mtu: 1450
```

**Comment by silviokuehn** [comment]
I had a similar issue. We have a docker-in-docker build container within a Rancher 2 / Kubernetes environment. I had to decrease the MTU of the inner docker service by adding `"mtu": 1200` into `/etc/docker/daemon.json`. The host servers MTU is 1500.

daemon.json
```
{
    "mtu": 1200
}
```

**Comment by JohnnyElvis** [comment]
> I had a similar issue. We have a docker-in-docker build container within a Rancher 2 / Kubernetes environment. I had to decrease the MTU of the inner docker service by adding `"mtu": 1200` into `/etc/docker/daemon.json`. The host servers MTU is 1500.
> 
> daemon.json
> 
> ```
> {
>     "mtu": 1200
> }
> ```

did the trick, thx!

**Comment by VengefulAncient** [comment]
We just got hit by this, running Drone docker plugin in a Kubernetes cluster. Decreasing the MTU to the value used by the `eth0` interface on the docker plugin container fixed the issue, thank you so much for sharing this fix.

What I absolutely do not understand is how it worked for almost a year without this workaround. We didn't change anything about our cluster or Drone setup, or the Alpine versions used in our pipelines. If someone has discovered more information about this, please do share.

**Comment by the0s** [comment]
After 4 hours of debugging managed to solve this by changing this in the gitlab-ci file:

```
services:
  name: docker:dind
```

TO 

```
services:
  - name: docker:dind
    command: ["--mtu=1300"]
```

source: https://github.com/docker-library/docker/issues/103#issuecomment-478619847

**Comment by heruscode** [comment]
On Codefresh runners you can set `mtu` in their [helm chart values](https://github.com/codefresh-io/venona/blob/d72f155bb32afdd94084eb09b9bf77d1ccef0400/.deploy/cf-runtime/values.yaml#L162) like:

```
re: 
  dindDaemon:
    mtu: 1400
```

**Comment by unseensenpai** [comment]
Unfortunately, I couldn't solve it either, so I wrote a retry mechanism in the YAMLs.

`RUN apk add --no-cache icu-libs icu-data-full tzdata || \
    (echo "Normal fail. Switching mirror..." && sed -i 's/dl-cdn.alpinelinux.org/dl-4.alpinelinux.org/g' /etc/apk/repositories && apk add --no-cache icu-libs icu-data-full tzdata) || \
    (echo "Retry 1..." && sleep 3 && apk add --no-cache icu-libs icu-data-full tzdata) || \
    (echo "Retry 2..." && sleep 5 && apk add --no-cache icu-libs icu-data-full tzdata) || \
    (echo "Retry 3..." && sleep 10 && apk add --no-cache icu-libs icu-data-full tzdata)`

**Comment by theoriginalgri** [comment]
I am not affected by this anymore but seem to have subscribed since I thought I was affected in the past.

I remember that we've been running into a similar issue on a Hetzner Dedicated Server, where the issue seemed to be the stateless firewall where the port range for incoming connections was not large enough and therefore connections to some alpine cdn servers broke after a given time (like 10 seconds into the download).

Even though `cat /proc/sys/net/ipv4/ip_local_port_range` outputs `32768-60999` as the needed port range, docker/containerd/alpine (don't remember who) seem to not care about this and use ports `1024-65535`

Here are example rules for that situation:

| #  | Name             | Version | Protokoll | Quell-IP             | Ziel-IP     | Quell-Port | Ziel-Port     | TCP-Flags                         | Aktion |
|----|------------------|---------|-----------|-----------------------|-------------|------------|---------------|-----------------------------------|--------|
| 1  | icmp             | ipv4    | icmp      | 0.0.0.0/0             | 0.0.0.0/0   | 0-65535    | 0-65535       |       | accept |
| 2  | tcp established  | ipv4    | tcp       | 0.0.0.0/0             | 0.0.0.0/0   | 0-65535    | 1024-65535    | ack                               | accept |
| 3  | tcp6 established | ipv6    | tcp       | 0.0.0.0/0             | 0.0.0.0/0   | 0-65535    | 1024-65535    | ack                               | accept |
