### ISSUE TITLE
operation timed out

### ISSUE THREAD

**Issue by longquan7** [gliderlabs/docker-alpine#330]
Step 6 : RUN apk add --update tar gnupg bash openssl && rm -rf /var/cache/apk/*
 ---> Running in 3d2e7804e300
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/aarch64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/main: operation timed out
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/community: operation timed out
WARNING: Ignoring APKINDEX.24d64ab1.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  bash (missing):
    required by: world[bash]
  gnupg (missing):
    required by: world[gnupg]
  openssl (missing):
    required by: world[openssl]
  tar (missing):
    required by: world[tar]
The command '/bin/sh -c apk add --update tar gnupg bash openssl && rm -rf /var/cache/apk/*' returned a non-zero code: 4

**Comment by andyshinn** [comment]
This is generally just a temporary networking issue with the host. If you are reliably able to reproduce this, then please provide some more information for debugging:

* Docker client and server version
* `Dockerfile` being built
* Output of `curl -v -S  http://dl-cdn.alpinelinux.org/alpine/v3.6/community/aarch64/APKINDEX.tar.gz > /dev/null` from host

It could be a local networking issue or something with the CDN. Both are not something we can really immediately fix.

**Comment by longquan7** [comment]
@andyshinn OK,thanks

**Comment by Alan-R** [comment]
I have this same issue, but when I try and fetch the things being complained about from the same host that's doing the docker build, it works immediately. Is this due to the '301' code below?

apk --update add openssl zip jq
 ---> Running in 5ce13d3981b2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/main: operation timed out
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.6/community: operation timed out
WARNING: Ignoring APKINDEX.24d64ab1.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  jq (missing):
    required by: world[jq]
  openssl (missing):
    required by: world[openssl]
  zip (missing):
    required by: world[zip]
The command '/bin/sh -c apk --update add openssl zip jq' returned a non-zero code: 3

To verify:
$ curl -v -S http://dl-cdn.alpinelinux.org/alpine/v3.6/community/aarch64/APKINDEX.tar.gz > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to dl-cdn.alpinelinux.org port 80 (#0)
*   Trying 151.101.32.249...
* Connected to dl-cdn.alpinelinux.org (151.101.32.249) port 80 (#0)
> GET /alpine/v3.6/community/aarch64/APKINDEX.tar.gz HTTP/1.1
> User-Agent: curl/7.29.0
> Host: dl-cdn.alpinelinux.org
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/octet-stream
< Last-Modified: Tue, 17 Oct 2017 13:44:10 GMT
< ETag: "59e6092a-56535"
< Accept-Ranges: bytes
< Content-Length: 353589
< Accept-Ranges: bytes
< Date: Wed, 18 Oct 2017 19:40:42 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-iad2642-IAD
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1508355642.084996,VS0,VE106
< 
{ [data not shown]
100  345k  100  345k    0     0   458k      0 --:--:-- --:--:-- --:--:--  457k
* Connection #0 to host dl-cdn.alpinelinux.org left intact


OR
curl -v -S http://dl-cdn.alpinelinux.org/alpine/v3.6/main
* About to connect() to dl-cdn.alpinelinux.org port 80 (#0)
*   Trying 151.101.32.249...
* Connected to dl-cdn.alpinelinux.org (151.101.32.249) port 80 (#0)
> GET /alpine/v3.6/main HTTP/1.1
> User-Agent: curl/7.29.0
> Host: dl-cdn.alpinelinux.org
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: nginx
< Content-Type: text/html
< Location: http://dl-4.alpinelinux.org/alpine/v3.6/main/
< Content-Length: 178
< Accept-Ranges: bytes
< Date: Wed, 18 Oct 2017 19:45:35 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-iad2127-IAD
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1508355935.067507,VS0,VE114
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
* Connection #0 to host dl-cdn.alpinelinux.org left intact

**Comment by Alan-R** [comment]
If I follow that moved comment, then I get this result (which looks correct):
 curl -v -S http://dl-4.alpinelinux.org/alpine/v3.6/main/
```
* About to connect() to dl-4.alpinelinux.org port 80 (#0)
*   Trying 147.75.32.21...
* Connected to dl-4.alpinelinux.org (147.75.32.21) port 80 (#0)
> GET /alpine/v3.6/main/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: dl-4.alpinelinux.org
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Date: Wed, 18 Oct 2017 19:48:13 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< 
<html>
<head><title>Index of /alpine/v3.6/main/</title></head>
<body bgcolor="white">
<h1>Index of /alpine/v3.6/main/</h1><hr><pre><a href="../">../</a>
<a href="aarch64/">aarch64/</a>                                           18-Oct-2017 10:53                   -
<a href="armhf/">armhf/</a>                                             18-Oct-2017 10:53                   -
<a href="ppc64le/">ppc64le/</a>                                           18-Oct-2017 10:54                   -
<a href="s390x/">s390x/</a>                                             20-Jul-2017 08:56                   -
<a href="x86/">x86/</a>                                               18-Oct-2017 10:53                   -
<a href="x86_64/">x86_64/</a>                                            18-Oct-2017 10:53                   -
</pre><hr></body>
</html>
* Connection #0 to host dl-4.alpinelinux.org left intact
```

**Comment by Alan-R** [comment]
$ docker -v
Docker version 1.13.1, build 092cba3

**Comment by andyshinn** [comment]
This is normal. The non-trailing `/` folder will be redirected to the one with a `/`. But it is odd that it is redirecting to `dl-4` as we are no longer using that upstream. But the pulling of APKINDEX does seem to be fine.

**Comment by Alan-R** [comment]
I'm currently investigating this as something wrong with our docker build configuration.

**Comment by Visteras** [comment]
@Alan-R you have any result? 
I have this problem :(
```
Step 1/6 : FROM alpine:latest
 ---> e21c333399e0
Step 2/6 : RUN apk --no-cache add ca-certificates
 ---> Running in 4240d0bbf177
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz: operation timed out
```
and
```
curl -v -S http://dl-cdn.alpinelinux.org/alpine/v3.6/community/aarch64/APKINDEX.tar.gz > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 151.101.184.249...
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* Connected to dl-cdn.alpinelinux.org (151.101.184.249) port 80 (#0)
> GET /alpine/v3.6/community/aarch64/APKINDEX.tar.gz HTTP/1.1
> Host: dl-cdn.alpinelinux.org
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/octet-stream
< Last-Modified: Tue, 05 Dec 2017 09:38:38 GMT
< ETag: "5a26691e-5662c"
< Accept-Ranges: bytes
< Content-Length: 353836
< Accept-Ranges: bytes
< Date: Wed, 06 Dec 2017 16:28:14 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-mdw17328-MDW
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1512577694.353614,VS0,VE220
<
{ [5472 bytes data]
100  345k  100  345k    0     0   156k      0  0:00:02  0:00:02 --:--:--  156k
* Connection #0 to host dl-cdn.alpinelinux.org left intact
```

**Comment by Alan-R** [comment]
If I recall correctly, my particular problem turned out to be a local configuration issue.

**Comment by ncopa** [comment]
I believe this can happen if you are accessing dl-cd.alpinelinux.org via a network link that has mtu lower than 1500, typically vpn, or other tunnels, pppoe and similar. It seems that PMTU does not work to fastly. You can normally work around it by configuring tcp mss clamping in your network.
