### ISSUE TITLE
(Yet another) Difference between gliderlabs/alpine and alpine

### ISSUE THREAD

**Issue by jamiejackson** [gliderlabs/docker-alpine#339]
What I found [here](https://github.com/gliderlabs/docker-alpine/issues/170#issuecomment-217285717) wasn't adequate for this fresh noob. I think a few examples would go a long way:

> For instance, in gliderlabs/alpine you can:
>* `do_magic --of-this-variety`
>* `foo bar`
>* `apk install stuff-that-is-hard-in-vanilla`

**Comment by tianon** [comment]
Are there any major concrete differences anymore?

Initially it was mostly just the `apk-install` script included in `gliderlabs/alpine` which set them apart, but since `apk add --no-cache` now exists to do essentially the same thing directly in `apk`, it is no longer necessary (as noted in https://github.com/gliderlabs/docker-alpine/issues/19#issuecomment-85667330).

**Comment by andyshinn** [comment]
I've updated the differences section at http://gliderlabs.viewdocs.io/docker-alpine/build/#user-content-differences. These days, there isn't a difference other than `apk-install`, which is no longer used.
