### ISSUE TITLE
Alpine using linux kernel?

### ISSUE THREAD

**Issue by AndyHoang** [gliderlabs/docker-alpine#355]
I trying using pyinotify (https://github.com/seb-m/pyinotify) to watch a mounted folder inside docker container.
Using base unbutu image is perfectly fine but alpine is not
I read the dependencies in pyinotify and notice this
```Linux ≥ 2.6.13```
I'm not sure if alpine can support this or is there any lib I need to install?
Trying to use an base image about 500mb is too much, that why I'm was using alpine for many of my images.
Any thought is welcome! Thanks

**Comment by ncopa** [comment]
Both ubuntu image and alpine image use the same kernel which is provided by the host, so if it works with the ubuntu image, then the kernel should be ok for alpine too.

What is the exact error message you get with alpine? Did you get a build error when `pip install pyinotify`? Did you install needed build dependencies like `build-base` and `python-dev` package? Is your network working? Did you run out of diskspace? Are you sure that you did not have any spelling errors? Did you try run `apt-get install` in alpine instead of `apk add`?

I can only make wild guesses without any exact error message or exact steps how to reproduce the problem.

**Comment by AndyHoang** [comment]
Hi!, Thanks for quick reponse ncopa,
The alpine image I used is the base one, then I install python into it. Some how it missing some other python library,
```FROM alpine:3.6
RUN apk add --no-cache python```

so somehow I got lucky trying the python alpine image, and it worked
`from python:2.7-alpine3.6`
I'm not sure where the missing point is, so now I'm keeping using the python alpine for the base image.
