### ISSUE TITLE
on docker alpine, node, centos install nodejs, always print Segmentation fault. 

### ISSUE THREAD

**Issue by Aidi2016** [gliderlabs/docker-alpine#404]
Apr 10 11:07:01 testnet03 systemd: Stopping user-0.slice.
Apr 10 11:07:48 testnet03 kernel: node[7499]: segfault at 17986 ip 0000000000017986 sp 00007fc239596438 error 14
Apr 10 11:08:52 testnet03 kernel: node[7564]: segfault at 17986 ip 0000000000017986 sp 00007f4a9e635438 error 14
Apr 10 11:09:55 testnet03 kernel: node[7637]: segfault at 17986 ip 0000000000017986 sp 00007f6c01053438 error 14
Apr 10 11:16:21 testnet03 dockerd: time="2018-04-10T11:16:21.019337918Z" level=info msg="Container 8fc2ad9d09c2d818468d111c28324d0eaa376f326e548c17418a45c7011c180b failed to exit within 10 seconds of signal 15 - using the force"
Apr 10 11:38:42 testnet03 kernel: node[8111]: segfault at 17986 ip 0000000000017986 sp 00007f07cf293438 error 14
Apr 10 11:38:46 testnet03 kernel: node[8171]: segfault at 17986 ip 0000000000017986 sp 00007f04b9b0a438 error 14
Apr 10 11:38:49 testnet03 kernel: node[8227]: segfault at 17986 ip 0000000000017986 sp 00007f8b1cc65438 error 14
Apr 10 11:38:53 testnet03 kernel: node[8283]: segfault at 17986 ip 0000000000017986 sp 00007f2025de4438 error 14
Apr 10 11:38:58 testnet03 kernel: node[8340]: segfault at 17986 ip 0000000000017986 sp 00007f05df912438 error 14
Apr 10 11:39:03 testnet03 kernel: node[8395]: segfault at 17986 ip 0000000000017986 sp 00007f73e0496438 error 14
Apr 10 11:39:10 testnet03 kernel: node[8452]: segfault at 17986 ip 0000000000017986 sp 00007fb71

**Comment by tianon** [comment]
This sounds like it's an issue with your host machine -- I'd recommend trying to reproduce it with a clean (freshly-installed) system hosted elsewhere.

If you're still able to reproduce, then I'd recommend writing up some very simple steps for others to be able to also reproduce the issue and posting to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) so someone can help you debug further and try to figure out the root cause. :+1:
