### ISSUE TITLE
Any plan to build docker-alpine based on alpine 3.8?

### ISSUE THREAD

**Issue by subjectxbj** [gliderlabs/docker-alpine#412]
Recently alpine 3.8 came out. Is there any plan to build a new docker image for alpine 3.8.

I found I can't build grpc on alpine 3.7. the version of "binutils" is still 2.28. So the "ld" tool does not support certain options like "-Wl", while 2.30 can support that. 

So it will be great if I can get a 3.8 alpine docker.

**Comment by tianon** [comment]
Alpine 3.8 is not released yet: https://alpinelinux.org

**Comment by lanmingle** [comment]
用 3.7 版本的包，真的太旧啦，edge 版本不敢用，等 3.8 维稳在升级呗。

**Comment by JoFAM** [comment]
3.8 is released now.

https://alpinelinux.org/posts/Alpine-3.8.0-released.html

@subjectxbj you can use alpine edge for that instead of alpine latest, or add the edge repos in your dockerfile. In mountainr dockerfiles, I use:

```
RUN echo '@edge http://nl.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories \ 
	&& echo '@edge http://nl.alpinelinux.org/alpine/edge/main' >> etc/apk/repositories \
	&& apk add --upgrade --no-cache apk-tools@edge

RUN ["apk", "add", "binutils@edge"]
```
You can tag the repos differently to use the 3.7 branch instead of edge, as the 3.7 has already the updated one. More info:

https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management#Repository_pinning

**Comment by ncopa** [comment]
While waiting for the official `alpine:3.8` I´d recommend something like:
````Dockerfile
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.8/main' > /etc/apk/repositories \ 
	&& echo 'http://dl-cdn.alpinelinux.org/alpine/v3.8/community' >> /etc/apk/repositories \
        && apk upgrade -U -a
````

**Comment by Vrtak-CZ** [comment]
https://github.com/gliderlabs/docker-alpine/tree/master/versions/library-3.8

**Comment by Vrtak-CZ** [comment]
https://github.com/docker-library/official-images/pull/4501
