### ISSUE TITLE
Not able to build dockerfile

### ISSUE THREAD

**Issue by hemantaltair** [gliderlabs/docker-alpine#457]
BLRMAC41-4:x86_64 hemant$ docker build -t alpine:3.8 -f Dockerfile .
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM scratch
 --->
Step 2/3 : ADD rootfs.tar.xz /
ADD failed: stat /var/lib/docker/tmp/docker-builder176183864/rootfs.tar.xz: no such file or directory
BLRMAC41-4:x86_64 hemant$

**Comment by hemantaltair** [comment]
Please respond ASAP.

**Comment by bebehei** [comment]
Dear Herman,

i'm sorry to hear that you have problems with the docker images. Given the urge of your problem, I'd like to help you out and respond ASAP to your questions.

Could you please provide some more information on the topic, especially about the branch and the folder?

Oh, and while I'm typing my reply, I'm seeing you're customer support payment is still due for the current month. [Please klick here to pay the customer support fees](https://www.linuxfoundation.org/about/donate/)!

Yours,
Customer support service

**Comment by tianon** [comment]
If you want to `docker build` this repository (instead of simply pulling it down via `docker pull alpine:3.X`), you'll have to do so from a proper clone of one of the artifact-containing branches, such as https://github.com/gliderlabs/docker-alpine/tree/rootfs/library-3.8/x86_64.

For example:

```console
$ docker build https://github.com/gliderlabs/docker-alpine.git#rootfs/library-3.8/x86_64:versions/library-3.8/x86_64
Sending build context to Docker daemon  1.767MB
Step 1/3 : FROM scratch
 ---> 
Step 2/3 : ADD rootfs.tar.xz /
 ---> 6f7381781a53
Step 3/3 : CMD ["/bin/sh"]
 ---> Running in 03616ae705c2
Removing intermediate container 03616ae705c2
 ---> 585e3c596326
Successfully built 585e3c596326
```

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
