### ISSUE TITLE
Missing AArch32 (ARMv7) support

### ISSUE THREAD

**Issue by lag-linaro** [gliderlabs/docker-alpine#463]
Do you plan to add support soon?

Support for ARMv6 and ARMv8 is already present.  There shouldn't be a reason for ARMv7 not to be.

**Comment by lag-linaro** [comment]
Found in a comment of the `build` script:

`# arm32v7 is not officially supported by Alpine, but arm32v6 should still work.`

a) Alpine does (now?) provide support for ARMv7 (AArch32, armhf, etc).
b) ARMv6 does not work on ARMv7

**Comment by lag-linaro** [comment]
@tianon do you have any idea why `x86_64` images are being pulled down on `armv7` platforms?
```
user@armv7:~/projects/docker-hub/docker-alpine [master]$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
407dbd16b126: Pull complete
57a7a83980e1: Pull complete
Digest: sha256:d9831ae63c5546ea8b849ff01ca6d57c066e013f5c8a8f4432cd59742beb52c7
Status: Downloaded newer image for alpine:latest

user@armv7:~/projects/docker-hub/docker-alpine [master]$ docker run -ti alpine:latest
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
exec format error
Error response from daemon: Cannot start container 4913f7d2dc171f081a157a887889980ec015641f7b8bdff071ade56b0363c43c: [8] System error: exec format error

user@armv7:~/projects/docker-hub/docker-alpine [master]$ docker cp 4913f7d2dc17:/bin/busybox .

user@armv7:~/projects/docker-hub/docker-alpine [master]$ file busybox
busybox: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
```

**Comment by tianon** [comment]
Sounds like an old or misconfigured or miscompiled Docker daemon -- I've tested very recently on an armv7 device with a recent Docker version and got the armv6 image as expected.

**Comment by richlander** [comment]
Are there any plans to produce an ARMv7 image @ [alpine](https://hub.docker.com/_/alpine)? The call out to ARMv7 in the [Alpine 3.9 announcement](https://twitter.com/alpinelinux/status/1090416212822110214) caught my attention! We'd love to know if that signals a commitment to produce ARMv7 container images. Microsoft will buy you a cake if it does!

I am a member of the .NET Core team at Microsoft. We publish images at [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet). We'd love to enable Alpine on ARM32, but are hesitant to enable our ARMv7 product on top of ARMv6 Alpine images. We assume that there has to be some downside to that option. I'd be interested in reading any docs that clarify what that configuration would mean in practice. We have many users who depend on our images, and expect us to only enable scenarios where he have high confidence, so we have to be pretty conservative.

The lack of Alpine on ARMv7 images prevent us from being able to promote Alpine as our preferred container OS since we can only use it for 64-bit. We use Debian and Ubuntu to cover both 32-bit and 64-bit scenarios, and offer convenient multi-arch tags for those OSes that cover that breadth.

Please consider publishing Alpine ARM32v7 images. Thank you. We'll be very quick to adopt them!

**Comment by ncopa** [comment]
> Please consider publishing Alpine ARM32v7 images. Thank you. We'll be very quick to adopt them!

This is fixed with https://github.com/docker-library/official-images/pull/5516
