### ISSUE TITLE
find -empty does not work and outputs help text instead result

### ISSUE THREAD

**Issue by godfuture** [gliderlabs/docker-alpine#470]
Currently trying to use cloud commander in docker, but face an issue using find in their console (https://github.com/coderaiser/cloudcmd/issues/217). As the docker image is based on docker-alpine, I came here to open the ticket in the right place.

Dependencies of the underlying images finally refer to gliderlabs/alpine:3.8.

**Comment by ncopa** [comment]
Short answer: run `apk add findutils`.

Long answer: The `-empty` option is not specified in [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html) so you cannot expect it to be portable  and work everywhere. Instead you need to use the implementation that behaves the way you expect it to (since it is not standardized it may in theory behave different depending on implementation). I assume the GNU findutils' `find` is doing what you expect.
