### ISSUE TITLE
Apparent DNS failure in Docker image alpine:3.8, nslookup: can't resolve '(null)'

### ISSUE THREAD

**Issue by chrisinmtown** [gliderlabs/docker-alpine#476]
Seeing odd DNS behavior in Docker image alpine:3.8. I'm baffled that nslookup complains yet finds the IP address.  In comparison, ping works perfectly. See below.  This little test runs a docker container to resolve the name of the host VM. If I can get that working the next test will be to have the docker container resolve the name of other running containers. 

Traced this back from behavior in an OpenJDK image, in which Java cannot resolve host names.  I'd really prefer to use an Alpine version of a Java/JRE image, it's half the size of a non-Alpine (debian) Java/JRE image, but this network glitch is kind of a killer.

So far I've run this test under a plain Ubuntu VM running docker 17.05.0-ce and under Kubernetes running docker version 18.09.1. Same behavior in both. I know there are many external variables that might affect this so it might not be an Alpine issue at all, altho issue #255 sure seems to be related. 

Would someone possibly take a minute to explain please? Thanks in advance.

```
me@host-dev1-vm01-core:~$ docker run alpine:3.8 nslookup host-dev1-vm01-core

nslookup: can't resolve '(null)': Name does not resolve
Name:      host-dev1-vm01-core
Address 1: 10.1.0.6
me@host-dev1-vm01-core:~$ docker run alpine:3.8 ping host-dev1-vm01-core
PING host-dev1-vm01-core (10.1.0.6): 56 data bytes
64 bytes from 10.1.0.6: seq=0 ttl=64 time=0.061 ms
64 bytes from 10.1.0.6: seq=1 ttl=64 time=0.133 ms
^C
--- host-dev1-vm01-core ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.061/0.097/0.133 ms
```

**Comment by bboreham** [comment]
The BusyBox `nslookup`, which Alpine uses, does two lookups, one for the DNS server and one for the name you asked for.  This can be seen [here](https://git.busybox.net/busybox/tree/networking/nslookup.c#n217).

In your example `nslookup` did resolve the name `host-dev1-vm01-core` to the address `10.1.0.6`.

The line `can't resolve '(null)'` says that, at that point, it didn't know what its DNS server was.
Looking at the [code that might initialize it](http://git.musl-libc.org/cgit/musl/tree/src/network/res_init.c), we see why.
Sorry, I ran out of time chasing down the reason for that. Hope this is of some help.

**Comment by bboreham** [comment]
It’s not really a failure at all; it’s just a program printing something out that isn’t helpful or interesting. 

What Alpine nslookup does has no bearing on what a Java program does.

**Comment by chrisinmtown** [comment]
I ran nslookup to check whether the running container is able to resolve a name to an IP address.  I hear you saying, nslookup is not a reliable indicator. Please suggest a better way.

**Comment by bboreham** [comment]
I'm not saying it is not a reliable indicator, I'm saying the line where it prints `can't resolve '(null)'` is not related to what you want to know.

Check the return code from `nslookup`; ignore that line.

**Comment by chrisinmtown** [comment]
I have not yet figured out the problem, pls see below for native Java debugging stuff, hope this will help other people.

Simple java class
```
import java.net.InetAddress;
public class ResolveHostName {
	public static void main(String[] args) throws Exception {
		if (args.length != 1)
			throw new IllegalArgumentException("Usage: program host-name-to-resolve");
		System.out.println("Resolving " + args[0]);
		System.out.println(InetAddress.getByName(args[0]).toString());
	}
}
```

Build script
```
#!/bin/bash
# compile test class and package into jar
set -e -x
javac ResolveHostName.java
jar cvfe res-host-name.jar ResolveHostName ResolveHostName.class
```

Dockerfile
```
FROM openjdk:8-jre-alpine
COPY res-host-name.jar /
ENTRYPOINT ["java", "-jar", "res-host-name.jar"]
```

**Comment by jcperezamin** [comment]
Please, include this fix in all alpine versions https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-409603030

**Comment by EmpireJones** [comment]
@jcperezamin - I think that's a different issue. Also, I think that'd just be hacking in a workaround for the underlying issue, which is a linux kernel bug to be fixed in v5.0 - https://github.com/torvalds/linux/commit/4e35c1cb9460240e983a01745b5f29fe3a4d8e39

**Comment by inter169** [comment]
1. yes, you can ignore the alpine (busybox) nslookup outputting message "... can't resolve '(null)'", it's unnecessary, if you set the second param as a NS, the msg would be gone away:
```
# nslookup wx.qlogo.cn 203.205.142.155
Server:    203.205.142.155
Address 1: 203.205.142.155
```
and the relative busybox codes (e.g. alpine3.8 is using http://busybox.net/downloads/busybox-1.28.4.tar.bz2 , networking/nslookup.c, function nslookup_main) and the debugging logs with strace showed that the program tried the PTR qurey (reverse DNS) for the NS server first of all, you got that msg because of the empty global NS server at the initialized time.

2. my codes implements (*workaround* https://github.com/kubernetes/kubernetes/issues/56903#issuecomment-409603030) removed the default behavior to decrease that dns timed out issue, at the docker image tier, please consider the pros and cons (it worked well for me, the nodejs/java/go/c++/python application that no needs ipv6), and the perfect solution to solve the dns timed out would be others (kernel conntrack racy fixes, local node dns cache ).

I have been running most of applications (java/go/nodejs/c/c++/python) based on my customized alpine docker for 1+ years. 
and highly recommend running some debugging with strace, tcpdump on the docker, you would run docker on the privileged mode to get more system capability,
can you please post some strace / tcpdump logs here?

thanks,
harper

**Comment by xbmono** [comment]
I have similar issue in our Kubernetes cluster when I try to get ip of the DNS server

```
/ # nslookup kube-dns.kube-system.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      kube-dns.kube-system.svc.cluster.local
Address 1: 192.168.0.10 kube-dns.kube-system.svc.cluster.local
```

**Comment by WeihanLi** [comment]
fixed with
``` yaml
spec:
  template:
    metadata:
      labels:
        app: activityreservation
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
```

refer to <https://github.com/WeihanLi/ActivityReservation/blob/dev/reservation-deployment.yaml> for details

**Comment by bboreham** [comment]
@xbmono if you are complaining about "can't resolve '(null)'" please read my explanation at https://github.com/gliderlabs/docker-alpine/issues/476#issuecomment-457124840.  It is nothing to worry about. If something else, I suggest you open a new issue.

**Comment by Antiarchitect** [comment]
Having the same issue with Alpine 3.9. Is there any workaround for this?

**Comment by vedmant** [comment]
I have the same problem with alpine:3.10

**Comment by sashok2k** [comment]
> I have the same problem with alpine:3.10

Same for me..

**Comment by sscholl** [comment]
same here node:alpine brings this problem

**Comment by WeihanLi** [comment]
any workaround with docker here?

**Comment by ncopa** [comment]
> The BusyBox `nslookup`, which Alpine uses, does two lookups, one for the DNS server and one for the name you asked for. This can be seen [here](https://git.busybox.net/busybox/tree/networking/nslookup.c#n217).
> 
This was very useful. There are apparently a different nslookup implementation available in busybox which can be enabled with `CONFIG_FEATURE_NSLOOKUP_BIG` and the comments there says that it is compatible with musl. I wil enable that and see if i can backport it to `alpine:3.11` at least.

BTW, the official docker image has moved to https://github.com/alpinelinux/docker-alpine. Since this was a config option in upstream alpine, it would have been good if it was reported upstream to 
https://gitlab.alpinelinux.org/alpine/aports

**Comment by ncopa** [comment]
This should be fixed in alpinelinux/aports@e5c984f68aabb28de623a7e3ada5a223c2b66d77 and will be available next release (`alpine:3.11.3`). Meanwhile, you can get it with `apk upgrade -U -a`

**Comment by jgoeres** [comment]
We just switched to Alpine 3.11.3 and now nslookup is failing for us unless we explicitly specify the DNS server IP (which is of course not an option), e.g.

    foo@/#nslookup abs
    Server:         127.0.0.11
    Address:        127.0.0.11:53
    ** server can't find abs.<OUR_INTRANET_DOMAIN>.: NXDOMAIN
    ** server can't find abs.<OUR_INTRANET_DOMAIN>.: NXDOMAIN
    [...]

versus

    foo@/#nslookup abs 127.0.0.11
    Server:         127.0.0.11
    Address:        127.0.0.11:53

    Non-authoritative answer:

    Non-authoritative answer:
    Name:   abs
    Address: 172.27.0.12

Ping etc. work flawlessly. 
Alas, we are using nslookup in some of our startscripts to defer starting of the actual application inside the container until another container shows up in DNS (cause the 3rd party tool we are using considers a failed DNS lookup a non-recoverable error...).

**Comment by jlegido** [comment]
A temporary workaround which worked for me: try to create the docker container in host mode:

```
--network host
```
