### ISSUE TITLE
Alpine 3.12 : pamtester-0.1.2-r0: BAD signature

### ISSUE THREAD

**Issue by fred-lab** [gliderlabs/docker-alpine#547]
Hello
When I try to install Pamtester with Alpine 3.12 on a ARM processor (docker on a RPI 3b+), I have this error : pamtester-0.1.2-r0: BAD signature

/ # apk add pamtester
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/armv7/APKINDEX.tar.gz
(1/1) Installing pamtester (0.1.2-r0)
ERROR: pamtester-0.1.2-r0: BAD signature
1 error; 11 MiB in 33 packages

Thank you.

**Comment by ncopa** [comment]
This is because of mixing 3.12 with edge. We are currently rebuilding edge packages for 32 bit architectures due to [musl 1.2 update](https://lists.alpinelinux.org/~alpine/devel/%3C20200721171650.48fa63a4%40ncopa-desktop.copa.dup.pw%3E) in edge. The old packages are cached at fastly and result in checksum mismatches.

This should fix it:
```
curl -X PURGE http://dl-cdn.alpinelinux.org/alpine/edge/testing/armv7/pamtester-0.1.2-r0.apk
```

Please note that musl 1.2 intrudes 64 bit `time_t` for the 32bit arches so there is a small chance that things will go bad (if time_t is used in public headers in some of the dependencies). May be an idea to only use edge repos for everything or ask for move pamtester to community and backport to 3.12 stable.

**Comment by ncopa** [comment]
I have purged the cache for all edge/*/armhf packages. should be ok now.

**Comment by fred-lab** [comment]
Thanks you for your help
