### ISSUE TITLE
alpine package build environment in docker

### ISSUE THREAD

**Issue by SydOps** [gliderlabs/docker-alpine#72]
@andyshinn 

Reading this wiki (http://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package), I am interesting to create a docker image that I needn't prepare the build environment every time to create an alpine package.

It will save a lot of time and speed us to buld and publish package in alpine. 

Do you have any exist `Dockerfile` for reference?

**Comment by andyshinn** [comment]
I actually have an image for building packages at https://github.com/andyshinn/docker-alpine-abuild. It sounds like you might want to peek at the `Dockerfile` there (or just use the image from https://hub.docker.com/r/andyshinn/alpine-abuild/).

Also, be sure to check out the https://github.com/andyshinn/docker-alpine-abuild/tree/refactor_env_volumes branch as I am refactoring it to use volumes and environment variables instead of embedding private keys in the build context.

**Comment by SydOps** [comment]
Nice, will have a try
